let parks = [
  {
    Name: "Acadia",
    State: "Maine",
    Size: "49,076.63",
    Image: "acadia.jpg",
  },
  {
    Name: "American Samoa",
    State: "American Samoa",
    Size: "8,256.67",
    Image: "americanSamoa.jpg",
  },
  {
    Name: "Arches",
    State: "Utah",
    Size: "76,678,98",
    Image: "Arches.jpg",
  },
  {
    Name: "Badlands",
    State: "South Dakota",
    Size: "242,755.94",
    Image: "badlands.jpg",
  },
  {
    Name: "Big Bend",
    State: "Texas",
    Size: "801,163,21",
    Image: "bigBend.jpg",
  },
  {
    Name: "Black Canyon of the Gunnison",
    State: "Colorado",
    Size: "341,620",
    Image: "blackCanyon.jpg",
  },
  {
    Name: "Bryce Canyon",
    State: "Utah",
    Size: "35,835.08",
    Image: "bryceCanyon.jpg",
  },
  {
    Name: "Canyonlands",
    State: "Utah",
    Size: "337,597.83",
    Image: "canyonLands.jpg",
  },
  {
    Name: "Capitol Reef",
    State: "Utah",
    Size: "241,904.50",
    Image: "capitolReef.jfif",
  },
  {
    Name: "Carlsbad Caverns",
    State: "New Mexico",
    Size: "46,766.45",
    Image: "carlsbad.jpg",
  },
  {
    Name: "Channel Islands",
    State: "California",
    Size: "249,561.00",
    Image: "channelIslands.jfif",
  },
  {
    Name: "Congaree",
    State: "South Carolina",
    Size: "26,476.47",
    Image: "congaree.jpg",
  },
  {
    Name: "Crater Lake",
    State: "Oregon",
    Size: "183,224.05",
    Image: "craterLake.jpg",
  },
  {
    Name: "Cuyahoga Valley",
    State: "Ohio",
    Size: "32,571.88",
    Image: "cuyahoga.jpg",
  },
  {
    Name: "Death Valley",
    State: "California/Nevada",
    Size: "3,408,406.73",
    Image: "deathValley.jpg",
  },
  {
    Name: "Denali",
    State: "Alaska",
    Size: "4,740,911.16",
    Image: "denali.jpg",
  },
  {
    Name: "Dry Tortugas",
    State: "Florida",
    Size: "64,701.22",
    Image: "dryTortugas.jpg",
  },
  {
    Name: "Everglades",
    State: "Florida",
    Size: "1,508,938.57",
    Image: "everglades.jpg",
  },
  {
    Name: "Gates of the Arctic",
    State: "Alaska",
    Size: "7,523,897.45",
    Image: "gatesOfArtic.jpg",
  },
  {
    Name: "Glacier",
    State: "Montana",
    Size: "1,013,125.99",
    Image: "glacier.jpg",
  },
  {
    Name: "Glacier Bay",
    State: "Alaska",
    Size: "3,223,383,43",
    Image: "glacierBay.jpg",
  },
  {
    Name: "Grand Canyon",
    State: "Arizona",
    Size: "1,201,647.03",
    Image: "grandCanyon.jpg",
  },
  {
    Name: "Grand Teton",
    State: "Wyoming",
    Size: "310,044.36",
    Image: "grandTeton.jpg",
  },
  {
    Name: "Great Basin",
    State: "Nevada",
    Size: "77,180.00",
    Image: "greatBasin.jpg",
  },
  {
    Name: "Great Sand Dunes",
    State: "Colorado",
    Size: "107,341.87",
    Image: "greatSandDunes.jpg",
  },
  {
    Name: "Great Smoky Mountains",
    State: "North Carolina/Tennessee",
    Size: "522,426.88",
    Image: "greatSmokeyMountains.jpg",
  },
  {
    Name: "Guadalupe Mountains",
    State: "Texas",
    Size: "86,367.10",
    Image: "guadalupe.jpg",
  },
  {
    Name: "Haleakala",
    State: "Hawaii",
    Size: "33,264.62",
    Image: "haleakala.jpg",
  },
  {
    Name: "Hawai’i Volcanoes",
    State: "Hawaii",
    Size: "325,605.28",
    Image: "volcanoes.jpg",
  },
  {
    Name: "Hot Springs",
    State: "Arkansas",
    Size: "5,554.15",
    Image: "hotSprings.jpg",
  },
  {
    Name: "Isle Royale",
    State: "Michigan",
    Size: "571,790.30",
    Image: "isleRoyal.jpg",
  },
  {
    Name: "Joshua Tree",
    State: "Calidornia",
    Size: "795,155.85",
    Image: "joshuaTree.jpg",
  },
  {
    Name: "Katmai",
    State: "Alaska",
    Size: "3,674,529.33",
    Image: "katMai.jpg",
  },
  {
    Name: "Kenai Fjords",
    State: "Alaska",
    Size: "669,650.05",
    Image: "kenaiFjors.jpg",
  },
  {
    Name: "Kings Canyon",
    State: "California",
    Size: "461,901,20",
    Image: "kingsCanyon.jpg",
  },
  {
    Name: "Kobuk Valley",
    State: "Alaska",
    Size: "1,750,716.16",
    Image: "kobuk.jpg",
  },
  {
    Name: "Lake Clark",
    State: "Alaska",
    Size: "2,619,816.49",
    Image: "lakeClark.jpg",
  },
  {
    Name: "Lassen Volcanic",
    State: "California",
    Size: "106,589.02",
    Image: "lassen.jpg",
  },
  {
    Name: "Mammoth Cave",
    State: "Kentucky",
    Size: "54,011.91",
    Image: "mammoth.jpg",
  },
  {
    Name: "Mesa Verde",
    State: "Colorado",
    Size: "52,485.17",
    Image: "mesaVerde.jpg",
  },
  {
    Name: "Mount Rainier",
    State: "Washington",
    Size: "236,381.64",
    Image: "mountRainier.jpg",
  },
  {
    Name: "North Cascades",
    State: "Washington",
    Size: "504,780.94",
    Image: "northCascades.jpg",
  },
  {
    Name: "Olympic",
    State: "Washington",
    Size: "922,649.41",
    Image: "olympic.jpg",
  },
  {
    Name: "Petrified Forest",
    State: "Arizona",
    Size: "221,390.21",
    Image: "petrifiedForest.jpg",
  },
  {
    Name: "Pinnacles",
    State: "California",
    Size: "26,685.73",
    Image: "pinnacles.jpg",
  },
  {
    Name: "Redwood",
    State: "California",
    Size: "138,999.37",
    Image: "redwood.jpg",
  },
  {
    Name: "Rocky Mountain",
    State: "Colorado",
    Size: "265,807.25",
    Image: "rockyMountain.jpg",
  },
  {
    Name: "Saguaro",
    State: "Arizona",
    Size: "92,867.42",
    Image: "saguaro.jpg",
  },
  {
    Name: "Sequoia",
    State: "California",
    Size: "404,062.63",
    Image: "sequoia.jpg",
  },
  {
    Name: "Shenandoah",
    State: "Virginia",
    Size: "199,223.77",
    Image: "shenandoah.jpg",
  },
  {
    Name: "Virgin Islands",
    State: "U.S Virgin Islands",
    Size: "15,052.53",
    Image: "virginIslands.jpg",
  },
  {
    Name: "Voyageurs",
    State: "Minnesota",
    Size: "218,222.35",
    Image: "voyageurs.jpg",
  },
  {
    Name: "Wind Cave",
    State: "South Dakota",
    Size: "33,970.84",
    Image: "windCave.jpg",
  },
  {
    Name: "Wrangell–St. Elias",
    State: "Alaska",
    Size: "8,823,146,48",
    Image: "wrangell.jpg",
  },
  {
    Name: "Yellowstone",
    State: "Wyoming/Montana/Idaho",
    Size: "2,219,790,71",
    Image: "yellowstone.jpg",
  },
  {
    Name: "Yosemite",
    State: "California",
    Size: "761,747,50",
    Image: "yosemite.jpg",
  },
  {
    Name: "Zion",
    State: "Utah",
    Size: "147,242,66",
    Image: "zion.jpg",
  },
];

export default parks;
